"""Constants and sensor definitions for the Synsynk Solar Inverter integration."""
from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfTemperature,
)

DOMAIN = "synsynk"
CONF_FILE_PATH = "file_path"
DEFAULT_FILE_PATH = "/tmp/solar.status"


@dataclass(frozen=True, kw_only=True)
class SynsynkSensorEntityDescription(SensorEntityDescription):
    """Extends SensorEntityDescription with JSON location info."""

    category: str = ""
    json_key: str = ""


SENSOR_DESCRIPTIONS: tuple[SynsynkSensorEntityDescription, ...] = (
    # ── Battery ──────────────────────────────────────────────────────────────
    SynsynkSensorEntityDescription(
        key="battery_current",
        name="Battery Current",
        category="Battery",
        json_key="Battery Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="battery_power",
        name="Battery Power",
        category="Battery",
        json_key="Battery Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="battery_soc",
        name="Battery SOC",
        category="Battery",
        json_key="Battery SOC",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="battery_status",
        name="Battery Status",
        category="Battery",
        json_key="Battery Status",
    ),
    SynsynkSensorEntityDescription(
        key="battery_temperature",
        name="Battery Temperature",
        category="Battery",
        json_key="Battery Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="battery_voltage",
        name="Battery Voltage",
        category="Battery",
        json_key="Battery Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="total_battery_charge",
        name="Total Battery Charge",
        category="Battery",
        json_key="Total Battery Charge",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SynsynkSensorEntityDescription(
        key="total_battery_discharge",
        name="Total Battery Discharge",
        category="Battery",
        json_key="Total Battery Discharge",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # ── Grid ─────────────────────────────────────────────────────────────────
    SynsynkSensorEntityDescription(
        key="daily_energy_bought",
        name="Daily Energy Bought",
        category="Grid",
        json_key="Daily Energy Bought",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SynsynkSensorEntityDescription(
        key="daily_energy_sold",
        name="Daily Energy Sold",
        category="Grid",
        json_key="Daily Energy Sold",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SynsynkSensorEntityDescription(
        key="external_ct_l1_power",
        name="External CT L1 Power",
        category="Grid",
        json_key="External CT L1 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="external_ct_l2_power",
        name="External CT L2 Power",
        category="Grid",
        json_key="External CT L2 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="grid_voltage_l1",
        name="Grid Voltage L1",
        category="Grid",
        json_key="Grid Voltage L1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="grid_voltage_l2",
        name="Grid Voltage L2",
        category="Grid",
        json_key="Grid Voltage L2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="internal_ct_l1_power",
        name="Internal CT L1 Power",
        category="Grid",
        json_key="Internal CT L1 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="internal_ct_l2_power",
        name="Internal CT L2 Power",
        category="Grid",
        json_key="Internal CT L2 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="total_energy_bought",
        name="Total Energy Bought",
        category="Grid",
        json_key="Total Energy Bought",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SynsynkSensorEntityDescription(
        key="total_energy_sold",
        name="Total Energy Sold",
        category="Grid",
        json_key="Total Energy Sold",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SynsynkSensorEntityDescription(
        key="total_grid_power",
        name="Total Grid Power",
        category="Grid",
        json_key="Total Grid Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="total_grid_production",
        name="Total Grid Production",
        category="Grid",
        json_key="Total Grid Production",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # ── Inverter ──────────────────────────────────────────────────────────────
    SynsynkSensorEntityDescription(
        key="inverter_ac_temperature",
        name="AC Temperature",
        category="Inverter",
        json_key="AC Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="communication_board_version",
        name="Communication Board Version",
        category="Inverter",
        json_key="Communication Board Version No.",
    ),
    SynsynkSensorEntityDescription(
        key="control_board_version",
        name="Control Board Version",
        category="Inverter",
        json_key="Control Board Version No.",
    ),
    SynsynkSensorEntityDescription(
        key="inverter_current_l1",
        name="Current L1",
        category="Inverter",
        json_key="Current L1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="inverter_current_l2",
        name="Current L2",
        category="Inverter",
        json_key="Current L2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="inverter_dc_temperature",
        name="DC Temperature",
        category="Inverter",
        json_key="DC Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="gen_power",
        name="Generator Power",
        category="Inverter",
        json_key="Gen Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="gen_connected_status",
        name="Generator Connected Status",
        category="Inverter",
        json_key="Gen-connected Status",
    ),
    SynsynkSensorEntityDescription(
        key="grid_connected_status",
        name="Grid Connected Status",
        category="Inverter",
        json_key="Grid-connected Status",
    ),
    SynsynkSensorEntityDescription(
        key="inverter_id",
        name="Inverter ID",
        category="Inverter",
        json_key="Inverter ID",
        entity_registry_enabled_default=False,
    ),
    SynsynkSensorEntityDescription(
        key="inverter_l1_power",
        name="Inverter L1 Power",
        category="Inverter",
        json_key="Inverter L1 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="inverter_l2_power",
        name="Inverter L2 Power",
        category="Inverter",
        json_key="Inverter L2 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="running_status",
        name="Running Status",
        category="Inverter",
        json_key="Running Status",
    ),
    SynsynkSensorEntityDescription(
        key="time_of_use",
        name="Time of Use",
        category="Inverter",
        json_key="Time of use",
    ),
    SynsynkSensorEntityDescription(
        key="inverter_total_power",
        name="Inverter Total Power",
        category="Inverter",
        json_key="Total Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="work_mode",
        name="Work Mode",
        category="Inverter",
        json_key="Work Mode",
    ),
    # ── Solar ─────────────────────────────────────────────────────────────────
    SynsynkSensorEntityDescription(
        key="daily_solar_production",
        name="Daily Solar Production",
        category="Solar",
        json_key="Daily Production",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SynsynkSensorEntityDescription(
        key="micro_inverter_power",
        name="Micro-inverter Power",
        category="Solar",
        json_key="Micro-inverter Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="pv1_current",
        name="PV1 Current",
        category="Solar",
        json_key="PV1 Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="pv1_power",
        name="PV1 Power",
        category="Solar",
        json_key="PV1 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="pv1_voltage",
        name="PV1 Voltage",
        category="Solar",
        json_key="PV1 Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="pv2_current",
        name="PV2 Current",
        category="Solar",
        json_key="PV2 Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="pv2_power",
        name="PV2 Power",
        category="Solar",
        json_key="PV2 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="pv2_voltage",
        name="PV2 Voltage",
        category="Solar",
        json_key="PV2 Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="total_solar_production",
        name="Total Solar Production",
        category="Solar",
        json_key="Total Production",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # ── Load (Upload category) ────────────────────────────────────────────────
    SynsynkSensorEntityDescription(
        key="daily_load_consumption",
        name="Daily Load Consumption",
        category="Upload",
        json_key="Daily Load Consumption",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SynsynkSensorEntityDescription(
        key="load_l1_power",
        name="Load L1 Power",
        category="Upload",
        json_key="Load L1 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="load_l2_power",
        name="Load L2 Power",
        category="Upload",
        json_key="Load L2 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="load_voltage",
        name="Load Voltage",
        category="Upload",
        json_key="Load Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SynsynkSensorEntityDescription(
        key="smartload_enable_status",
        name="SmartLoad Enable Status",
        category="Upload",
        json_key="SmartLoad Enable Status",
    ),
    SynsynkSensorEntityDescription(
        key="total_load_consumption",
        name="Total Load Consumption",
        category="Upload",
        json_key="Total Load Consumption",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SynsynkSensorEntityDescription(
        key="total_load_power",
        name="Total Load Power",
        category="Upload",
        json_key="Total Load Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
)
